include:
  - board: seeeduino_xiao_ble
    shield: ergonaut_one_left
    cmake-args: -DCONFIG_ZMK_POINTING=y
    artifact-name: n1
  - board: seeeduino_xiao_ble
    shield: ergonaut_one_right
    cmake-args: -DCONFIG_ZMK_POINTING=y
    artifact-name: n2
  - board: seeeduino_xiao_ble
    shield: ergonaut_one_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_POINTING=y
    artifact-name: n3_ergonaut_one_left_studio
  - board: seeeduino_xiao_ble
    shield: ergonaut_one_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_POINTING=y
    artifact-name: n4_ergonaut_one_right_studio
  - board: seeeduino_xiao_ble
    shield: settings_reset
