include:
  - board: seeeduino_xiao_ble
    shield: ergonaut_one_left
    cmake-args: -DCONFIG_ZMK_POINTING=y
    artifact-name: n1_left
  - board: seeeduino_xiao_ble
    shield: ergonaut_one_right
    cmake-args: -DCONFIG_ZMK_POINTING=y
    artifact-name: n2_right
  - board: seeeduino_xiao_ble
    shield: ergonaut_one_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_POINTING=y
    artifact-name: n3_left_studio
  - board: seeeduino_xiao_ble
    shield: ergonaut_one_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_POINTING=y
    artifact-name: n4_right_studio
  - board: seeeduino_xiao_ble
    shield: settings_reset
